// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqlzthetcaktudilsyxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxbHp0aGV0Y2FrdHVkaWxzeXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY3NDEyNzgsImV4cCI6MjA4MjMxNzI3OH0.3jHp3dTy70AtVpPz5Flxeex6hXajApl23UEC0zx0VCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
